# Generated by Django 5.2.3 on 2025-07-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Software Development', 'Software Development'), ('Design and Architecture', 'Design and Architecture'), ('Graphic Design', 'Graphic Design')], max_length=64),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
