# Generated by Django 5.2.3 on 2025-07-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_service_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='service/'),
        ),
    ]
