# Generated by Django 5.2.3 on 2025-07-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_social_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('Github', 'Github'), ('X', 'X')], max_length=255, unique=True),
        ),
    ]
