# Generated by Django 5.2.3 on 2025-07-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_bookmark_support_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='support',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
