# Generated by Django 5.2.3 on 2025-07-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_bookmark_status_support_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='read',
        ),
        migrations.RemoveField(
            model_name='support',
            name='read',
        ),
    ]
