# Generated by Django 5.2.3 on 2025-07-31 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_project_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='name',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('Github', 'Github'), ('X', 'X')], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('user', 'name')},
        ),
    ]
