# Generated by Django 5.2.3 on 2025-08-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_alter_social_name_alter_social_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='social',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Software Development', 'Software Development'), ('UI/UX Design', 'UI/UX Design'), ('Graphic Design', 'Graphic Design'), ('Mobile App Development', 'Mobile App Development'), ('Game Development', 'Game Development'), ('Data Analysis', 'Data Analysis'), ('DevOps', 'DevOps'), ('Cloud Solutions', 'Cloud Solutions'), ('AI & Machine Learning', 'AI & Machine Learning'), ('Cybersecurity', 'Cybersecurity'), ('Database Management', 'Database Management'), ('Embedded Systems', 'Embedded Systems'), ('AR/VR Development', 'AR/VR Development'), ('Technical Writing', 'Technical Writing'), ('API Development', 'API Development'), ('E-commerce Solutions', 'E-commerce Solutions'), ('Automation Scripting', 'Automation Scripting'), ('Digital Marketing', 'Digital Marketing'), ('Blockchain Development', 'Blockchain Development'), ('Architecture & Design', 'Architecture & Design')], max_length=64),
        ),
    ]
