# Generated by Django 5.2.3 on 2025-08-05 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_alter_social_unique_together_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
